"""empty message

Revision ID: 6f997f71d42b
Revises: 
Create Date: 2023-08-28 08:59:28.651644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f997f71d42b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_index('titulo_unico_album')

    op.drop_table('album')
    op.drop_table('album_cancion')
    op.drop_table('usuario')
    op.drop_table('cancion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('minutos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('segundos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interprete', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contrasena', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('album_cancion',
    sa.Column('album_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cancion_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], name='album_cancion_ibfk_1'),
    sa.ForeignKeyConstraint(['cancion_id'], ['cancion.id'], name='album_cancion_ibfk_2'),
    sa.PrimaryKeyConstraint('album_id', 'cancion_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('album',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('anio', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descripcion', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('medio', mysql.ENUM('DISCO', 'CASETE', 'CD'), nullable=True),
    sa.Column('usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], name='album_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.create_index('titulo_unico_album', ['usuario', 'titulo'], unique=False)

    # ### end Alembic commands ###
